# Generated by Django 3.2.13 on 2022-05-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('algorithms', 'Algorithms'), ('data structures', 'Data Structures'), ('computer programming', 'Computer Programming'), ('blockchain', 'Blockchain'), ('database', 'Database'), ('seo', 'Seo'), ('news', 'News')], default='algorithms', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
